apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orgaudi.fullname" . }}-config
  labels:
    {{- include "orgaudi.labels" . | nindent 4 }}
data:
  APP_NAME: "OrgAudi"
  ENVIRONMENT: {{ .Values.global.environment }}
  LOG_LEVEL: "INFO"
  FRONTEND_DOMAIN: {{ .Values.global.domain }}
  BACKEND_WORKERS: "4"
